name: Java CI 

on:
  schedule:
  - cron: "41 12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name : Checkout Repository
      uses: actions/checkout@v2
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        
    - name: Compile Java
      run: javac -d out src/com/HelloWorld.java
      
    - name: Run Main Class
      run: java -cp out src/com/HelloWorld
